// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/shanghai.proto

package com.zhoujie.hive;

public final class FactPBHive {
  private FactPBHive() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ShangHai extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ShangHai> {
    // Use ShangHai.newBuilder() to construct.
    private ShangHai() {
      initFields();
    }
    private ShangHai(boolean noInit) {}
    
    private static final ShangHai defaultInstance;
    public static ShangHai getDefaultInstance() {
      return defaultInstance;
    }
    
    public ShangHai getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhoujie.hive.FactPBHive.internal_static_hive_ShangHai_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhoujie.hive.FactPBHive.internal_static_hive_ShangHai_fieldAccessorTable;
    }
    
    // optional string region_name = 1;
    public static final int REGION_NAME_FIELD_NUMBER = 1;
    private boolean hasRegionName;
    private java.lang.String regionName_ = "";
    public boolean hasRegionName() { return hasRegionName; }
    public java.lang.String getRegionName() { return regionName_; }
    
    // optional string info = 2;
    public static final int INFO_FIELD_NUMBER = 2;
    private boolean hasInfo;
    private java.lang.String info_ = "";
    public boolean hasInfo() { return hasInfo; }
    public java.lang.String getInfo() { return info_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!extensionsAreInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage.ExtendableMessage
        .ExtensionWriter extensionWriter = newExtensionWriter();
      if (hasRegionName()) {
        output.writeString(1, getRegionName());
      }
      if (hasInfo()) {
        output.writeString(2, getInfo());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRegionName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getRegionName());
      }
      if (hasInfo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getInfo());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.zhoujie.hive.FactPBHive.ShangHai parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.zhoujie.hive.FactPBHive.ShangHai parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.zhoujie.hive.FactPBHive.ShangHai parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.zhoujie.hive.FactPBHive.ShangHai parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.zhoujie.hive.FactPBHive.ShangHai parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.zhoujie.hive.FactPBHive.ShangHai parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.zhoujie.hive.FactPBHive.ShangHai parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.zhoujie.hive.FactPBHive.ShangHai parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.zhoujie.hive.FactPBHive.ShangHai parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.zhoujie.hive.FactPBHive.ShangHai parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhoujie.hive.FactPBHive.ShangHai prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.zhoujie.hive.FactPBHive.ShangHai, Builder> {
      private com.zhoujie.hive.FactPBHive.ShangHai result;
      
      // Construct using com.zhoujie.hive.FactPBHive.ShangHai.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.zhoujie.hive.FactPBHive.ShangHai();
        return builder;
      }
      
      protected com.zhoujie.hive.FactPBHive.ShangHai internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.zhoujie.hive.FactPBHive.ShangHai();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhoujie.hive.FactPBHive.ShangHai.getDescriptor();
      }
      
      public com.zhoujie.hive.FactPBHive.ShangHai getDefaultInstanceForType() {
        return com.zhoujie.hive.FactPBHive.ShangHai.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.zhoujie.hive.FactPBHive.ShangHai build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.zhoujie.hive.FactPBHive.ShangHai buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.zhoujie.hive.FactPBHive.ShangHai buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.zhoujie.hive.FactPBHive.ShangHai returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhoujie.hive.FactPBHive.ShangHai) {
          return mergeFrom((com.zhoujie.hive.FactPBHive.ShangHai)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.zhoujie.hive.FactPBHive.ShangHai other) {
        if (other == com.zhoujie.hive.FactPBHive.ShangHai.getDefaultInstance()) return this;
        if (other.hasRegionName()) {
          setRegionName(other.getRegionName());
        }
        if (other.hasInfo()) {
          setInfo(other.getInfo());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setRegionName(input.readString());
              break;
            }
            case 18: {
              setInfo(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string region_name = 1;
      public boolean hasRegionName() {
        return result.hasRegionName();
      }
      public java.lang.String getRegionName() {
        return result.getRegionName();
      }
      public Builder setRegionName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRegionName = true;
        result.regionName_ = value;
        return this;
      }
      public Builder clearRegionName() {
        result.hasRegionName = false;
        result.regionName_ = getDefaultInstance().getRegionName();
        return this;
      }
      
      // optional string info = 2;
      public boolean hasInfo() {
        return result.hasInfo();
      }
      public java.lang.String getInfo() {
        return result.getInfo();
      }
      public Builder setInfo(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasInfo = true;
        result.info_ = value;
        return this;
      }
      public Builder clearInfo() {
        result.hasInfo = false;
        result.info_ = getDefaultInstance().getInfo();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:hive.ShangHai)
    }
    
    static {
      defaultInstance = new ShangHai(true);
      com.zhoujie.hive.FactPBHive.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hive.ShangHai)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hive_ShangHai_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hive_ShangHai_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030src/proto/shanghai.proto\022\004hive\"9\n\010Shan" +
      "gHai\022\023\n\013region_name\030\001 \001(\t\022\014\n\004info\030\002 \001(\t*" +
      "\n\010\240\234\001\020\200\200\200\200\002B\036\n\020com.zhoujie.hiveB\nFactPBH" +
      "ive"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hive_ShangHai_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hive_ShangHai_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hive_ShangHai_descriptor,
              new java.lang.String[] { "RegionName", "Info", },
              com.zhoujie.hive.FactPBHive.ShangHai.class,
              com.zhoujie.hive.FactPBHive.ShangHai.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
